spring:
  application:
    name: planner

  datasource:
    url: jdbc:mysql://localhost:3306/planner
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true